/elevation_mapping_node:
  ros__parameters:
    #### Plugins ########
    plugin_config_file: '$(ros2 pkg prefix --share elevation_mapping_cupy)/config/setups/g1/g1_plugin_config.yaml'

    pointcloud_channel_fusions:
      rgb: 'color'
      default: 'average'

    image_channel_fusions:
      rgb: 'color'
      default: 'exponential'
      feat_.*: 'exponential'
      sem_.*: 'exponential'

    #### Publishers ########
    # topic_name:
    #   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
    #   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
    #   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

    publishers:
      elevation_map_raw:
        layers: ['elevation', 'traversability', 'variance', 'rgb', 'upper_bound']
        basic_layers: ['elevation', 'traversability']
        fps: 5.0
      elevation_map_filter:
        layers: ['min_filter', 'smooth', 'inpaint', 'elevation','rgb','max_categories']
        basic_layers: ['min_filter']
        fps: 3.0

    #### Subscribers ########
    subscribers:
      Livox:
        topic_name: /livox/lidar
        data_type: pointcloud